web_app/auth_app/urls.py
from django.urls import path
from .views import login_view, logout_view


app_name = 'auth_app'

urlpatterns = [
    path('', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

web_app/core/urls.py
from django.urls import path

from .views import index

urlpatterns = [
    path('', index),
]

web_app/video_server/urls.py
from django.urls import path, re_path

from .views import index, video_stream, camera_view

app_name = 'video_server'

urlpatterns = [
    path('', index, name='cameras'),
    path('video_stream/<str:hostname>', video_stream, name='video_stream'),
    path('camera/<str:hostname>/', camera_view, name='camera'),
]

web_app/web_app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from channels.routing import URLRouter
from video_server.routing import websocket_urlpatterns

urlpatterns = [
    path('', include('core.urls', )),
    path('auth/', include('auth_app.urls')),
    path('cameras/', include('video_server.urls')),
    path('admin/', admin.site.urls, name='admin'),
]

websocket_urlpatterns = [
    path('ws/', URLRouter(websocket_urlpatterns)),
]

web_app/auth_app/models.py
from django.db import models
from django.conf import settings

# Create your models here.

web_app/core/models.py
from django.db import models

# Create your models here.

web_app/video_server/models.py
from django.core.files.storage import FileSystemStorage
from django.db import models

fs = FileSystemStorage(location='images/cameras/')


class Camera(models.Model):
    id = models.AutoField(primary_key=True)
    hostname = models.CharField(max_length=50,verbose_name='IP адрес')
    is_active = models.BooleanField(default=False, db_index=True,verbose_name='Активная/неактивная камера')
    last_activities = models.DateTimeField(auto_now_add=True)

web_app/auth_app/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label='')
    password = forms.CharField(label='', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Username'})
        self.fields['password'].widget.attrs.update({'class': 'form-control', 'placeholder': '*******'})

web_app/auth_app/views.py
from django.contrib.auth import login, logout
from .decorator import authenticate_user, logout_user


@authenticate_user
def login_view(request, user=None):
    login(request, user)


@logout_user
def logout_view(request):
    logout(request)

web_app/core/views.py
from django.shortcuts import render


def index(request):
    # return HttpResponse("Index page")
    return render(request, 'index.html')

web_app/video_server/views.py
import time

from django.contrib.auth.decorators import login_required
from django.http.response import StreamingHttpResponse, HttpResponseServerError
from django.shortcuts import render

from .models import Camera
from stream import WebClient


@login_required(login_url='auth_app:login')
def index(request):
    cameras = Camera.objects.order_by('id')
    context = {'cameras': cameras}

    return render(request, 'cameras/index.html', context=context)


@login_required(login_url='auth_app:login')
def camera_view(request, hostname):
    return render(request, 'cameras/camera.html', {
        'hostname': hostname
    })


def gen(web_client, request):
    try:
        while True:
            time.sleep(0.03)
            frame = web_client.get_frame()
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')
    except Exception as e:
        return e


@login_required(login_url='auth_app:login')
def video_stream(request, hostname):
    try:
        return StreamingHttpResponse(gen(WebClient(hostname), request),
                                     content_type='multipart/x-mixed-replace; boundary=frame')
    except Exception as e:
        pass

web_app/auth_app/templates/auth_app/index.html
{% extends "base.html" %}

{% block title %}Login page{% endblock title %}

{% block content%}


<div class="vh-100 d-flex justify-content-center align-items-lg-center">
      <div class="container">
        <div class="row d-flex justify-content-center">
          <div class="col-12 col-md-8 col-lg-6">
            <div class="card bg-white">
              <div class="card-body p-5">
                  {% if messages %}
                      <ul class="messages">
                          {% for message in messages %}
                          <li>{{ message }}</li>
                          {% endfor %}
                      </ul>
                {% endif %}
                <form action="{% url 'auth_app:login' %}" method="POST" class="mb-3 mt-md-4">
                  <div class="mb-3">
                    <label class="form-label ">User name</label>
                      {{login_form.username}}
                  </div>
                  <div class="mb-3">
                      <label class="form-label ">Password</label>
                      {{login_form.password}}
                  </div>
                  <div class="d-grid">
                      <button class="btn btn-outline-dark" type="submit">Login</button>
                  </div>
                    {% csrf_token %}
                </form>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content%}

web_app/auth_app/templates/auth_app/logged_out.html
{% extends "base.html" %}

{% block title %}Logged out page{% endblock title %}

{% block content%}
    <h1>Logged out</h1>
    <p>
        You have been successfully logged out.
        <hr>
        You can <a href="{% url 'auth_app:login' %}">log-in again</a>.
    </p>

{% endblock content%}

web_app/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">

    <title>{% block title %}Default title{% endblock title %}</title>
</head>

<body>
    {% include "navbar.html" %}
    <div class="container-fluid ">
        {% block content%}

        {% endblock content %}
    </div>

    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

web_app/core/templates/index.html
{% extends "base.html" %}

{% block title %}Index page{% endblock title %}

{% block content%}
  {% load static %}
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">Hello, world! <i class="fas fa-globe-americas"></i></h1>
            <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
            <hr class="my-4">
            <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <div class="card">
                    <div class="card-body">
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Special title treatment</h5>
                        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

web_app/core/templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="javascript:void(0)">Logo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mynavbar">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link" href="javascript:void(0)">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="javascript:void(0)">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="javascript:void(0)">Link</a>
            </li>
          </ul>
            {% if user.is_superuser %}
                    <div class="badge text-wrap" style="width: 6rem;">
                        <a class="nav-link" href="{% url 'admin:index' %}">admin panel</a>
                    </div>
            {% endif %}
            {% if user.is_authenticated %}
                    <div class="badge text-wrap" style="width: 6rem;">
                        Welcome, {{ user.get_username }}
                    </div>
                    <a href="{% url 'auth_app:logout' %}" class="btn btn-danger">Logout</a>
            {% else%}
                    <a href="{% url 'auth_app:login' %}" class="btn btn-danger">Login</a>
            {% endif %}
        </div>
      </div>
    </nav>

web_app/video_server/templates/cameras/camera.html
{% extends "base.html" %}

{% block title %}Camera page{% endblock title %}

{% block content%}
  {% load static %}
<div class="container">
  <div class="row row-tile">
    <div class="row">
    {{ hostname|json_script:"hostname" }}
            <div class="col-sm-8">
                <div class="card">
                    <div class="card-body">
                        <img class="col align-self-center" id='video' src="">
                        <input type="hidden" id="cam_off" value="{% static 'images/cameras/plug.png' %}">

                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-body">
                        <button class="actionButton" id="disconnect" onclick="">Disconnect</button>
                    </div>
                </div>
            </div>
    </div>
  </div>
</div>
      <script src="{% static 'js/video_stream.js' %}"></script>

        <script >
                connectSocket()
        </script>

{% endblock content%}

web_app/video_server/templates/cameras/index.html
{% extends "base.html" %}

{% block title %}Cameras page{% endblock title %}

{% block content%}
  {% load static %}
  <div class="row row-tile">
    <h1 style="text-align: center">Cameras</h1>
    <div class="col-md-12 tile">
      <div class="row row-tile text-black">
        {% for camera in cameras %}
          <div class="col-md-4 col-sm-4 col-xs-6 tile square ">
            <div class="tile-content" style="text-align: center">
              <h2>{{ camera.hostname }}</h2>
               <img style="width: 480px; height: 480px;" alt="Image description" src="{% static 'images/cameras/plug.png' %}"/>
<!--              {% if not camera.is_active%}-->
<!--                <img style="width: 480px; height: 480px;" alt="Image description" src="{% static 'images/cameras/plug.png' %}"/>-->
<!--              {%else%}-->
<!--                    <img src="{% url 'video_server:video_stream' hostname=camera.hostname %}" class="img-responsive" width="100%" alt="Responsive image">-->
<!--                {% endif %}-->
              <p>{{camera.is_active}}</p>
              <p>{{ camera.hostname }}</p>
              <p>{{ camera.last_activities | date:"d.m.Y H:i:s" }}</p>
            </div>
        </div>
       {% endfor %}
      </div>
    </div>
  </div>

    <div>
      <h2>{{ camera.num }}</h2>
      <p>{{camera.id}}</p>
      <p>{{camera.is_active}}</p>
      <p>{{ camera.ip_address }}</p>
      <p>{{ camera.last_activities | date:"d.m.Y H:i:s" }}</p>
    </div>

{% endblock content%}